#!/bin/sh

# 'dhcpHAsync'. Keeps ISC-DHCP daemon HA config in sync between two nodes.
# Copyright © 2015-2018 Mathias Bocquet (mbocquet@sekoya.org)

# script triggered by incron after dhcpd.conf.shared modification.

. /etc/default/isc-dhcp-server

LOCALCONF="${DHCPDv4_CONF:-/etc/dhcp/dhcpd.conf}"
SHAREDCONF="/etc/dhcp/dhcpd.conf.shared"
PEER="$(sed -n '/peer address/p' $LOCALCONF|awk '{print $3}'|tr -d ';')"

# reload DHCP server
service isc-dhcp-server force-reload

# sync shared DHCP server conf file on PEER node.
rsync -a ${SHAREDCONF} ${PEER}:${SHAREDCONF}
